services:
  - postgresql


language: node_js
node_js: 12.13.0

install:
  - npm install

script:
  - NODE_ENV=test npm run test

services:
  - postgresql

before_script:
  - psql -c 'create database strapi_test;' -U postgres

env:
    - DB_STRING='--dbclient=postgres --dbhost=localhost --dbport=5433 --dbname=strapi_test --dbusername=postgres --dbpassword='