language: node_js
node_js: 12.13.0
os: linux
dist: xenial

install:
  - npm install

script:
  - npm run test:travisci

services:
  - postgresql

before_script:
  - psql -c 'create database strapi_test;' -U postgres

env:
    - DB_STRING='--dbclient=postgres --dbhost=localhost --dbport=5433 --dbname=strapi_test --dbusername=postgres --dbpassword=' DATABASE_HOST=127.0.0.1 DATABASE_PORT=5432 DATABASE_NAME=strapi_test DATABASE_USERNAME=postgres DATABASE_PASSWORD= DATABASE_SSL=false

branches:
  only:
  - master